Add files via upload
nzzzde/Treni pull request #6
Opened 2024-09-27 16:49 UTC by danylofedas

2024-09-27 16:50 UTC, danylofedas reviewed
1

2024-09-28 14:15 UTC, Roxyprog requested changes
Make all comments in English. And this code must be in bmi.py

2024-09-28 15:53 UTC, Roxyprog requested changes

2024-09-28 15:53 UTC, Roxyprog commented on console/bmi.py
> -        print("Недостатня вага")
This row is unnecessary/

2024-09-28 15:53 UTC, Roxyprog commented on console/bmi.py
> +        print("Недостатня вага")
This row is unnecessary.

2024-09-28 15:53 UTC, Roxyprog commented on console/bmi.py
>          print("Нормальна вага")
This row is unnecessary/

2024-09-28 15:53 UTC, Roxyprog commented on console/bmi.py
>          print("Надмірна вага")
This row is unnecessary/

2024-09-28 15:53 UTC, Roxyprog commented on console/bmi.py
>          print("Ожиріння")
This row is unnecessary.

2024-09-28 17:59 UTC, Roxyprog approved these changes
Everything is ok)

2024-09-28 17:59 UTC, merged